In [1]:
import pandas as pd 
import numpy as np

In [2]:
# What are vectorized string operations?
# - These are string operations that can be applied to entire Series or DataFrame columns without the need for explicit loops. They are optimized for performance and can handle missing values gracefully.
a = np.array([1, 2, 3, 4])
a * 4

array([ 4,  8, 12, 16])

In [3]:
# problem in vectorized operations in vanila python 
s = ['cat', 'mat', None]
[i.startswith('c') for i in s]

AttributeError: 'NoneType' object has no attribute 'startswith'

In [ ]:
# How pandas solves this issue?

s = pd.Series(['cat', 'mat', None])
# str = string accessor
s.str.startswith('c')

# fast and optimized for larger datasets 
# why is it fast?
# - pandas uses Cython and other optimizations under the hood to speed up string operations. It also leverages vectorized operations, which are implemented in C and can process data in bulk, reducing the overhead of Python loops.

0     True
1    False
2    False
dtype: bool

In [6]:
# import titanic
df = pd.read_csv('titanic.csv')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [7]:
df['Name']

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: str

In [9]:
# Common functions 
# lower/upper/capitalize/title
df['Name'].str.lower().head()

0                              braund, mr. owen harris
1    cumings, mrs. john bradley (florence briggs th...
2                               heikkinen, miss. laina
3         futrelle, mrs. jacques heath (lily may peel)
4                             allen, mr. william henry
Name: Name, dtype: str

In [10]:
df['Name'].str.upper().head()

0                              BRAUND, MR. OWEN HARRIS
1    CUMINGS, MRS. JOHN BRADLEY (FLORENCE BRIGGS TH...
2                               HEIKKINEN, MISS. LAINA
3         FUTRELLE, MRS. JACQUES HEATH (LILY MAY PEEL)
4                             ALLEN, MR. WILLIAM HENRY
Name: Name, dtype: str

In [11]:
df['Name'].str.capitalize().head()

0                              Braund, mr. owen harris
1    Cumings, mrs. john bradley (florence briggs th...
2                               Heikkinen, miss. laina
3         Futrelle, mrs. jacques heath (lily may peel)
4                             Allen, mr. william henry
Name: Name, dtype: str

In [12]:
df['Name'].str.title().head()

0                              Braund, Mr. Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                               Heikkinen, Miss. Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                             Allen, Mr. William Henry
Name: Name, dtype: str

In [14]:
# len 
df['Name'].str.len().max()

np.int64(82)

In [16]:
df['Name'][df['Name'].str.len() == 82]

307    Penasco y Castellana, Mrs. Victor de Satode (M...
Name: Name, dtype: str

In [18]:
# strip
string = '   Hello, World!   '.strip()
string

'Hello, World!'

In [23]:
# split -> get 
df['lastname'] = df['Name'].str.split(',').str.get(0)

In [32]:
df[['title', 'firstname']] = df['Name'].str.split(',').str.get(1).str.strip().str.split(' ', n=1, expand=True)

In [33]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,lastname,title,firstname
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Braund,Mr.,Owen Harris
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Cumings,Mrs.,John Bradley (Florence Briggs Thayer)
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Heikkinen,Miss.,Laina
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Futrelle,Mrs.,Jacques Heath (Lily May Peel)
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Allen,Mr.,William Henry

In [34]:
df['title'].value_counts()

title
Mr.          517
Miss.        182
Mrs.         125
Master.       40
Dr.            7
Rev.           6
Major.         2
Mlle.          2
Col.           2
Don.           1
Mme.           1
Ms.            1
Lady.          1
Sir.           1
Capt.          1
the            1
Jonkheer.      1
Name: count, dtype: int64

In [36]:
# replace 
df['title'].str.replace('Ms.', 'Miss.').replace('Mlle.', 'Miss.').value_counts()

title
Mr.          517
Miss.        185
Mrs.         125
Master.       40
Dr.            7
Rev.           6
Major.         2
Col.           2
Don.           1
Mme.           1
Lady.          1
Sir.           1
Capt.          1
the            1
Jonkheer.      1
Name: count, dtype: int64

In [40]:
# filtering 
# startswith/endswith
df[df['firstname'].str.startswith('A')]['firstname']
# isdigit/isalpha/isalnum
df[df['firstname'].str.isdigit()]['firstname']

Series([], Name: firstname, dtype: object)

In [43]:
# applying regex 
# contains
# search john -> both case
df[df['firstname'].str.contains('john', case=False)]['firstname'].head()

1            John Bradley (Florence Briggs Thayer)
41     William John Robert (Dorothy Ann Wonnacott)
45                                    William John
98                         John T (Ada Julia Bone)
112                                     David John
Name: firstname, dtype: object

In [47]:
df[df['lastname'].str.contains('^[aeiouAEIOU].+[aeiouAEIOU]$', regex=True)]['lastname'].head()

30          Uruchurtu
49     Arnold-Franchi
207          Albimona
210               Ali
353    Arnold-Franchi
Name: lastname, dtype: object

In [49]:
# slicing 
df['Name'].str[:4]

0      Brau
1      Cumi
2      Heik
3      Futr
4      Alle
       ...
886    Mont
887    Grah
888    John
889    Behr
890    Dool
Name: Name, Length: 891, dtype: str