In [1]:
import numpy as np 
import pandas as pd

Series is 1D and DataFrames are 2D objects

In [5]:
# can we have multiple index? let's try  
index_val = [('cse', 2019), ('cse', 2020), ('cse', 2021), ('cse', 2022), ('ece', 2019), ('ece', 2020), ('ece', 2021), ('ece', 2022)]

In [6]:
a = pd.Series(data=np.random.randint(1, 100, 8), index=index_val)
a

(cse, 2019)    85
(cse, 2020)     3
(cse, 2021)    19
(cse, 2022)    48
(ece, 2019)    79
(ece, 2020)     8
(ece, 2021)    97
(ece, 2022)    91
dtype: int32

In [7]:
a[('cse', 2019)]

np.int32(85)

In [9]:
# The problem? 
# a['cse'] # Error

In [10]:
# The solution? MultiIndex objects!
# multiple index levels within a single index object.

In [11]:
# How to create mutliindex objects?
# 1. pd.MultiIndex.from_tuples()
index_val = [('cse', 2019), ('cse', 2020), ('cse', 2021), ('cse', 2022), ('ece', 2019), ('ece', 2020), ('ece', 2021), ('ece', 2022)]
multiindex = pd.MultiIndex.from_tuples(index_val, names=['dept', 'year'])
multiindex

MultiIndex([('cse', 2019),
            ('cse', 2020),
            ('cse', 2021),
            ('cse', 2022),
            ('ece', 2019),
            ('ece', 2020),
            ('ece', 2021),
            ('ece', 2022)],
           names=['dept', 'year'])

In [13]:
s = pd.Series(data=np.random.randint(1, 100, 8), index=multiindex)
s

dept  year
cse   2019     4
      2020    69
      2021    24
      2022    89
ece   2019    57
      2020    59
      2021    84
      2022    79
dtype: int32

In [14]:
s['cse']

year
2019     4
2020    69
2021    24
2022    89
dtype: int32

In [16]:
# 2. pd.MultiIndex.from_product()

pd.Series(np.random.randint(1, 100, 8), index=pd.MultiIndex.from_product([['cse', 'ece'], [2019, 2020, 2021, 2022]], names=['dept', 'year']))

dept  year
cse   2019    30
      2020    65
      2021    13
      2022    20
ece   2019    49
      2020    90
      2021    55
      2022    30
dtype: int32

In [17]:
# create series with multiindex 
s = pd.Series([1, 2, 3, 4, 5, 6, 7, 8], index=multiindex)

In [18]:
s

dept  year
cse   2019    1
      2020    2
      2021    3
      2022    4
ece   2019    5
      2020    6
      2021    7
      2022    8
dtype: int64

In [19]:
# how to fetch items from such a series?
s[('cse', 2019)]

np.int64(1)

In [20]:
s['cse']

year
2019    1
2020    2
2021    3
2022    4
dtype: int64

In [21]:
# unstack
s.unstack()

year  2019  2020  2021  2022
dept
cse      1     2     3     4
ece      5     6     7     8

In [22]:
s.unstack(level=0)

dept  cse  ece
year
2019    1    5
2020    2    6
2021    3    7
2022    4    8

In [23]:
# stack 
s.unstack().stack()

dept  year
cse   2019    1
      2020    2
      2021    3
      2022    4
ece   2019    5
      2020    6
      2021    7
      2022    8
dtype: int64

In [24]:
# mutliIndex dataframe

In [25]:
branch_df1 = pd.DataFrame(
    [
        [1, 2],
        [3, 4],
        [5, 6],
        [7, 8],
        [9, 10],
        [11, 12],
        [13, 14],
        [15, 16],
    ],
    index=multiindex,
    columns=['avg_package', 'students']
)

branch_df1

           avg_package  students
dept year
cse  2019            1         2
     2020            3         4
     2021            5         6
     2022            7         8
ece  2019            9        10
     2020           11        12
     2021           13        14
     2022           15        16

In [26]:
branch_df1.loc['cse']

      avg_package  students
year
2019            1         2
2020            3         4
2021            5         6
2022            7         8

In [28]:
branch_df1.loc['ece']

      avg_package  students
year
2019            9        10
2020           11        12
2021           13        14
2022           15        16

In [29]:
branch_df1.loc[:, 'avg_package']

dept  year
cse   2019     1
      2020     3
      2021     5
      2022     7
ece   2019     9
      2020    11
      2021    13
      2022    15
Name: avg_package, dtype: int64

In [30]:
# multiindex df from columns perspective 
branch_df2 = pd.DataFrame(
    [
        [1, 2, 0, 0],
        [3, 4, 0, 0],
        [5, 6, 0, 0],
        [7, 8, 0, 0]
    ],
    index = [2019, 2020, 2021, 2022],
    columns = pd.MultiIndex.from_product([['delhi', 'mumbai'], ['avg_package','students']]))

In [31]:
branch_df2

           delhi               mumbai
     avg_package students avg_package students
2019           1        2           0        0
2020           3        4           0        0
2021           5        6           0        0
2022           7        8           0        0

In [32]:
branch_df2['delhi']

      avg_package  students
2019            1         2
2020            3         4
2021            5         6
2022            7         8

In [33]:
branch_df2['mumbai']['avg_package']

2019    0
2020    0
2021    0
2022    0
Name: avg_package, dtype: int64

In [34]:
branch_df2.loc[2019]

delhi   avg_package    1
        students       2
mumbai  avg_package    0
        students       0
Name: 2019, dtype: int64

In [35]:
# MultiIndex df in terms of both rows and columns
branch_df3 = pd.DataFrame(
    np.random.randint(1, 100, (8, 4)),
    index=multiindex,
    columns=pd.MultiIndex.from_product([['delhi', 'mumbai'], ['avg_package','students']])
)

In [36]:
branch_df3

                delhi               mumbai
          avg_package students avg_package students
dept year
cse  2019          43       97          99       13
     2020          83       55          56       51
     2021          10       84          95        7
     2022          75       96          39       23
ece  2019          87       42          47       29
     2020          10        7          49       78
     2021          95       74          70       94
     2022          55       82          27       64

Stacking and Unstacking

In [38]:
branch_df1

           avg_package  students
dept year
cse  2019            1         2
     2020            3         4
     2021            5         6
     2022            7         8
ece  2019            9        10
     2020           11        12
     2021           13        14
     2022           15        16

In [39]:
branch_df1.unstack()

     avg_package                students
year        2019 2020 2021 2022     2019 2020 2021 2022
dept
cse            1    3    5    7        2    4    6    8
ece            9   11   13   15       10   12   14   16

In [40]:
branch_df1.unstack().unstack()

             year  dept
avg_package  2019  cse      1
                   ece      9
             2020  cse      3
                   ece     11
             2021  cse      5
                   ece     13
             2022  cse      7
                   ece     15
students     2019  cse      2
                   ece     10
             2020  cse      4
                   ece     12
             2021  cse      6
                   ece     14
             2022  cse      8
                   ece     16
dtype: int64

In [42]:
branch_df1.unstack().stack()

           avg_package  students
dept year
cse  2019            1         2
     2020            3         4
     2021            5         6
     2022            7         8
ece  2019            9        10
     2020           11        12
     2021           13        14
     2022           15        16

In [43]:
branch_df1.unstack().stack().stack()

dept  year
cse   2019  avg_package     1
            students        2
      2020  avg_package     3
            students        4
      2021  avg_package     5
            students        6
      2022  avg_package     7
            students        8
ece   2019  avg_package     9
            students       10
      2020  avg_package    11
            students       12
      2021  avg_package    13
            students       14
      2022  avg_package    15
            students       16
dtype: int64

In [44]:
branch_df2

           delhi               mumbai
     avg_package students avg_package students
2019           1        2           0        0
2020           3        4           0        0
2021           5        6           0        0
2022           7        8           0        0

In [45]:
branch_df2.unstack()

delhi   avg_package  2019    1
                     2020    3
                     2021    5
                     2022    7
        students     2019    2
                     2020    4
                     2021    6
                     2022    8
mumbai  avg_package  2019    0
                     2020    0
                     2021    0
                     2022    0
        students     2019    0
                     2020    0
                     2021    0
                     2022    0
dtype: int64

In [47]:
branch_df2.stack().stack()

2019  avg_package  delhi     1
                   mumbai    0
      students     delhi     2
                   mumbai    0
2020  avg_package  delhi     3
                   mumbai    0
      students     delhi     4
                   mumbai    0
2021  avg_package  delhi     5
                   mumbai    0
      students     delhi     6
                   mumbai    0
2022  avg_package  delhi     7
                   mumbai    0
      students     delhi     8
                   mumbai    0
dtype: int64

In [48]:
branch_df3

                delhi               mumbai
          avg_package students avg_package students
dept year
cse  2019          43       97          99       13
     2020          83       55          56       51
     2021          10       84          95        7
     2022          75       96          39       23
ece  2019          87       42          47       29
     2020          10        7          49       78
     2021          95       74          70       94
     2022          55       82          27       64

In [49]:
branch_df3.unstack()

           delhi                                             mumbai            \
     avg_package                students                avg_package
year        2019 2020 2021 2022     2019 2020 2021 2022        2019 2020 2021
dept
cse           43   83   10   75       97   55   84   96          99   56   95
ece           87   10   95   55       42    7   74   82          47   49   70


          students
year 2022     2019 2020 2021 2022
dept
cse    39       13   51    7   23
ece    27       29   78   94   64

In [50]:
branch_df3.unstack().unstack()

                     year  dept
delhi   avg_package  2019  cse     43
                           ece     87
                     2020  cse     83
                           ece     10
                     2021  cse     10
                           ece     95
                     2022  cse     75
                           ece     55
        students     2019  cse     97
                           ece     42
                     2020  cse     55
                           ece      7
                     2021  cse     84
                           ece     74
                     2022  cse     96
                           ece     82
mumbai  avg_package  2019  cse     99
                           ece     47
                     2020  cse     56
                           ece     49
                     2021  cse     95
                           ece     70
                     2022  cse     39
                           ece     27
        students     2019  cse     13
                           ece     29
                     2020  cse     51
                           ece     78
                     2021  cse      7
                           ece     94
                     2022  cse     23
                           ece     64
dtype: int32

Working with multiindex dataframes

In [51]:
# head and tail 
branch_df3

                delhi               mumbai
          avg_package students avg_package students
dept year
cse  2019          43       97          99       13
     2020          83       55          56       51
     2021          10       84          95        7
     2022          75       96          39       23
ece  2019          87       42          47       29
     2020          10        7          49       78
     2021          95       74          70       94
     2022          55       82          27       64

In [52]:
branch_df3.head()

                delhi               mumbai
          avg_package students avg_package students
dept year
cse  2019          43       97          99       13
     2020          83       55          56       51
     2021          10       84          95        7
     2022          75       96          39       23
ece  2019          87       42          47       29

In [53]:
branch_df3.shape

(8, 4)

In [54]:
branch_df3.info()

<class 'pandas.DataFrame'>
MultiIndex: 8 entries, ('cse', np.int64(2019)) to ('ece', np.int64(2022))
Data columns (total 4 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   (delhi, avg_package)   8 non-null      int32
 1   (delhi, students)      8 non-null      int32
 2   (mumbai, avg_package)  8 non-null      int32
 3   (mumbai, students)     8 non-null      int32
dtypes: int32(4)
memory usage: 750.0+ bytes

In [55]:
branch_df3.duplicated()

dept  year
cse   2019    False
      2020    False
      2021    False
      2022    False
ece   2019    False
      2020    False
      2021    False
      2022    False
dtype: bool

In [56]:
branch_df3.isnull().sum()

delhi   avg_package    0
        students       0
mumbai  avg_package    0
        students       0
dtype: int64

In [57]:
# Extracting rows single 
branch_df3

                delhi               mumbai
          avg_package students avg_package students
dept year
cse  2019          43       97          99       13
     2020          83       55          56       51
     2021          10       84          95        7
     2022          75       96          39       23
ece  2019          87       42          47       29
     2020          10        7          49       78
     2021          95       74          70       94
     2022          55       82          27       64

In [60]:
branch_df3.loc[('cse', 2022)]

delhi   avg_package    75
        students       96
mumbai  avg_package    39
        students       23
Name: (cse, 2022), dtype: int32

In [61]:
# multiple rows 
branch_df3.loc[('cse', 2019):('ece', 2020):2]

                delhi               mumbai
          avg_package students avg_package students
dept year
cse  2019          43       97          99       13
     2021          10       84          95        7
ece  2019          87       42          47       29

In [62]:
# Extracting columns 
branch_df3['delhi']

           avg_package  students
dept year
cse  2019           43        97
     2020           83        55
     2021           10        84
     2022           75        96
ece  2019           87        42
     2020           10         7
     2021           95        74
     2022           55        82

In [63]:
branch_df3['delhi']['students']

dept  year
cse   2019    97
      2020    55
      2021    84
      2022    96
ece   2019    42
      2020     7
      2021    74
      2022    82
Name: students, dtype: int32

In [64]:
branch_df3

                delhi               mumbai
          avg_package students avg_package students
dept year
cse  2019          43       97          99       13
     2020          83       55          56       51
     2021          10       84          95        7
     2022          75       96          39       23
ece  2019          87       42          47       29
     2020          10        7          49       78
     2021          95       74          70       94
     2022          55       82          27       64

In [67]:
branch_df3.loc[:, [('delhi', 'students'), ('mumbai', 'avg_package')]]

             delhi      mumbai
          students avg_package
dept year
cse  2019       97          99
     2020       55          56
     2021       84          95
     2022       96          39
ece  2019       42          47
     2020        7          49
     2021       74          70
     2022       82          27

In [68]:
# sort index 
branch_df3

                delhi               mumbai
          avg_package students avg_package students
dept year
cse  2019          43       97          99       13
     2020          83       55          56       51
     2021          10       84          95        7
     2022          75       96          39       23
ece  2019          87       42          47       29
     2020          10        7          49       78
     2021          95       74          70       94
     2022          55       82          27       64

In [70]:
branch_df3.sort_index(ascending=False)

                delhi               mumbai
          avg_package students avg_package students
dept year
ece  2022          55       82          27       64
     2021          95       74          70       94
     2020          10        7          49       78
     2019          87       42          47       29
cse  2022          75       96          39       23
     2021          10       84          95        7
     2020          83       55          56       51
     2019          43       97          99       13

In [71]:
branch_df3.sort_index(ascending=[False, True])

                delhi               mumbai
          avg_package students avg_package students
dept year
ece  2019          87       42          47       29
     2020          10        7          49       78
     2021          95       74          70       94
     2022          55       82          27       64
cse  2019          43       97          99       13
     2020          83       55          56       51
     2021          10       84          95        7
     2022          75       96          39       23

In [72]:
branch_df3.sort_index(level=1, ascending=False)

                delhi               mumbai
          avg_package students avg_package students
dept year
ece  2022          55       82          27       64
cse  2022          75       96          39       23
ece  2021          95       74          70       94
cse  2021          10       84          95        7
ece  2020          10        7          49       78
cse  2020          83       55          56       51
ece  2019          87       42          47       29
cse  2019          43       97          99       13

In [73]:
# multiindex dataframe(col) -> transpose 
branch_df3.T

dept                cse                 ece
year               2019 2020 2021 2022 2019 2020 2021 2022
delhi  avg_package   43   83   10   75   87   10   95   55
       students      97   55   84   96   42    7   74   82
mumbai avg_package   99   56   95   39   47   49   70   27
       students      13   51    7   23   29   78   94   64

In [74]:
# swaplevel 
branch_df3

                delhi               mumbai
          avg_package students avg_package students
dept year
cse  2019          43       97          99       13
     2020          83       55          56       51
     2021          10       84          95        7
     2022          75       96          39       23
ece  2019          87       42          47       29
     2020          10        7          49       78
     2021          95       74          70       94
     2022          55       82          27       64

In [75]:
branch_df3.swaplevel()

                delhi               mumbai
          avg_package students avg_package students
year dept
2019 cse           43       97          99       13
2020 cse           83       55          56       51
2021 cse           10       84          95        7
2022 cse           75       96          39       23
2019 ece           87       42          47       29
2020 ece           10        7          49       78
2021 ece           95       74          70       94
2022 ece           55       82          27       64

In [76]:
branch_df3.swaplevel(axis=1)

          avg_package students avg_package students
                delhi    delhi      mumbai   mumbai
dept year
cse  2019          43       97          99       13
     2020          83       55          56       51
     2021          10       84          95        7
     2022          75       96          39       23
ece  2019          87       42          47       29
     2020          10        7          49       78
     2021          95       74          70       94
     2022          55       82          27       64

Long vs Wide Data

Wide format is where we have a single row for every data point with multiple columns to hold the valeus of various attributes.

Long format is where, for each data point we have as many rows as the number of attributesand each row contains the value of a particular attribute for a given data point.

In [77]:
# melt -> wide to long format 
pd.DataFrame({'cse': [120]})

   cse
0  120

In [78]:
pd.DataFrame({'cse': [120]}).melt()

  variable  value
0      cse    120

In [ ]:
pd.DataFrame({'cse': [120], 'ece': [100], 'mech': [50]})

   cse  ece  mech
0  120  100    50

In [81]:
pd.DataFrame({'cse': [120], 'ece': [100], 'mech': [50]}).melt(var_name='branch', value_name='students')

  branch  students
0    cse       120
1    ece       100
2   mech        50

In [82]:
pd.DataFrame(
    {
        'branch': ['cse', 'ece', 'mech'],
        '2020': [100, 150, 60],
        '2021': [120, 130, 80],
        '2022': [130, 120, 90]
    }
)

  branch  2020  2021  2022
0    cse   100   120   130
1    ece   150   130   120
2   mech    60    80    90

In [84]:
pd.DataFrame(
    {
        'branch': ['cse', 'ece', 'mech'],
        '2020': [100, 150, 60],
        '2021': [120, 130, 80],
        '2022': [130, 120, 90]
    }
).melt(id_vars=['branch'], var_name='year', value_name='students')

  branch  year  students
0    cse  2020       100
1    ece  2020       150
2   mech  2020        60
3    cse  2021       120
4    ece  2021       130
5   mech  2021        80
6    cse  2022       130
7    ece  2022       120
8   mech  2022        90

In [96]:
death = pd.read_csv('time_series_covid19_deaths_global.csv')
confirm = pd.read_csv('time_series_covid19_confirmed_global.csv')

In [97]:
death.head()

,Province/State,Country/Region,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,12/24/22,12/25/22,12/26/22,12/27/22,12/28/22,12/29/22,12/30/22,12/31/22,1/1/23,1/2/23
0,NaN,Afghanistan,33.93911,67.709953,0,0,0,0,0,0,...,7845,7846,7846,7846,7846,7847,7847,7849,7849,7849
1,NaN,Albania,41.15330,20.168300,0,0,0,0,0,0,...,3595,3595,3595,3595,3595,3595,3595,3595,3595,3595
2,NaN,Algeria,28.03390,1.659600,0,0,0,0,0,0,...,6881,6881,6881,6881,6881,6881,6881,6881,6881,6881
3,NaN,Andorra,42.50630,1.521800,0,0,0,0,0,0,...,165,165,165,165,165,165,165,165,165,165
4,NaN,Angola,-11.20270,17.873900,0,0,0,0,0,0,...,1928,1928,1928,1930,1930,1930,1930,1930,1930,1930

In [98]:
death.shape

(289, 1081)

In [99]:
confirm.head()

,Province/State,Country/Region,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,12/24/22,12/25/22,12/26/22,12/27/22,12/28/22,12/29/22,12/30/22,12/31/22,1/1/23,1/2/23
0,NaN,Afghanistan,33.93911,67.709953,0,0,0,0,0,0,...,207310,207399,207438,207460,207493,207511,207550,207559,207616,207627
1,NaN,Albania,41.15330,20.168300,0,0,0,0,0,0,...,333749,333749,333751,333751,333776,333776,333806,333806,333811,333812
2,NaN,Algeria,28.03390,1.659600,0,0,0,0,0,0,...,271194,271198,271198,271202,271208,271217,271223,271228,271229,271229
3,NaN,Andorra,42.50630,1.521800,0,0,0,0,0,0,...,47686,47686,47686,47686,47751,47751,47751,47751,47751,47751
4,NaN,Angola,-11.20270,17.873900,0,0,0,0,0,0,...,104973,104973,104973,105095,105095,105095,105095,105095,105095,105095

In [100]:
death = death.melt(id_vars=['Province/State', 'Country/Region', 'Lat', 'Long'], var_name='date', value_name='death_count')
confirm = confirm.melt(id_vars=['Province/State', 'Country/Region', 'Lat', 'Long'], var_name='date', value_name='confirm_count')

In [101]:
confirm.merge(death, on=['Province/State', 'Country/Region', 'Lat', 'Long', 'date'], how='inner')

,Province/State,Country/Region,Lat,Long,date,confirm_count,death_count
0,NaN,Afghanistan,33.939110,67.709953,1/22/20,0,0
1,NaN,Albania,41.153300,20.168300,1/22/20,0,0
2,NaN,Algeria,28.033900,1.659600,1/22/20,0,0
3,NaN,Andorra,42.506300,1.521800,1/22/20,0,0
4,NaN,Angola,-11.202700,17.873900,1/22/20,0,0
...,...,...,...,...,...,...,...
311248,NaN,West Bank and Gaza,31.952200,35.233200,1/2/23,703228,5708
311249,NaN,Winter Olympics 2022,39.904200,116.407400,1/2/23,535,0
311250,NaN,Yemen,15.552727,48.516388,1/2/23,11945,2159
311251,NaN,Zambia,-13.133897,27.849332,1/2/23,334661,4024
311252,NaN,Zimbabwe,-19.015438,29.154857,1/2/23,259981,5637